(require 'lsp)
(require 'lsp-clients)
(require 'company)
(require 'company-lsp)
(require 'lsp-ui)
(defun lsp-settings()
  (define-key lsp-mode-map (kbd "C-c d") 'lsp-find-definition)
  (define-key lsp-mode-map (kbd "C-c r") 'lsp-find-references)
  (define-key lsp-mode-map (kbd "C-c i") 'lsp-find-implementation)
  (define-key lsp-mode-map (kbd "C-c C-r") 'lsp-rename)
  (define-key lsp-mode-map (kbd "C-c t") 'lsp-find-type-definitions)
  (define-key lsp-mode-map (kbd "C-c h") 'lsp-help-at-point))

(add-hook 'eglot-mode-hook 'eglot-settings)
(unless (package-installed-p 'lsp-mode)
  (package-install 'lsp-mode))
(unless (package-installed-p 'company-lsp)
  (package-install 'company-lsp))
(unless (package-installed-p 'lsp-ui)
  (package-install 'lsp-ui))
(push 'company-lsp company-backends)
(add-hook 'after-init-hook 'global-company-mode)
(add-hook 'lsp-mode-hook 'lsp-ui-mode)
(add-hook 'lsp-mode-hook 'lsp-settings)
(add-hook 'c++-mode-hook 'lsp)
(add-hook 'julia-mode-hook 'lsp)
